DROP TABLE IF EXISTS "users";

-- CREATE TABLE "users" (
--     "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     "username" VARCHAR
-- );
-- Does not allow users to add "user_id" manually !!
-- CREATE TABLE "users" (
--     "user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     "username" VARCHAR
-- );
-- CREATE TABLE "users" (
--     "user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     "username" VARCHAR
-- );
CREATE TABLE "users" (
    "user_id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2) PRIMARY KEY,
    "username" VARCHAR
);

INSERT INTO
    "users" ("username")
VALUES
    ('Guillermo'),
    ('Dixie');

SELECT
    *
FROM
    "users";